import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import CardList from "../components/Card/CardList";
import config from "../config";
import shuffle from "../util/shuffle";

export interface Props {
  config: typeof config;
}

const Home: NextPage<Props> = (props) => (
  <Layout>
    <Head>
      <title>Friends</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <CardList list={props.config} />
  </Layout>
);

Home.getInitialProps = async () => ({
  config: shuffle(config),
});

export default Home;
