import { NextPage } from "next";
import React from "react";
import Layout from "../components/Layout";
import Head from "next/head";
import styles from "../styles/Form.module.css";

const Login: NextPage = () => (
  <Layout>
    <Head>
      <title>Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.container}>
      <h2 style={{marginTop: "20vh"}} className={styles.title}>登录</h2>
      <form>
        <input type="text" placeholder="用户名" className={styles.input} />
        <input type="password" placeholder="密码" className={styles.input} />
        <input type="submit" className={styles.button} />
        <input type="reset" className={styles.button} />
      </form>
    </div>
  </Layout>
);

export default Login;
