import React from "react";
import type { NextPage } from "next";
import Note from "../components/Note";
import Layout from "../components/Layout";
import Head from "next/head";
import Form from "../components/Form";
import "animate.css";

const Login: NextPage = () => (
  <Layout>
    <Head>
      <title>Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="animate__animated animate__fadeIn">
      <Form />
      <Note />
    </div>
  </Layout>
);

export default Login;
