import type { NextPage } from "next";
import Table from "../components/Table/Table";
import Cell from "../components/Table/TableCell";
import Layout from "../components/Layout/Layout";
import Head from "next/head";
import "animate.css";
import Title from "../components/Title/Title";
import Anchor from "../components/Anchor/Anchor";
import Notice from "../components/Notice/Notice";

const Submit: NextPage = () => (
  <Layout width="600px">
    <Head>
      <title>Submit</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div
      className="animate__animated animate__fadeIn"
      style={{ display: "flex", flexDirection: "column", gap: "4px" }}
    >
      <Title>申请友链</Title>
      <Notice>
        请按照格式将友链申请发送至{" "}
        <a href="mailto:akarachen@outlook.com">akarachen@outlook.com</a>
      </Notice>
      <Title>站点信息</Title>
      <Table>
        <Cell name="站点标题">AkaraChen</Cell>
        <Cell name="站点图标">
          <Anchor href="https://github.com/akarachen.png">Link</Anchor>
        </Cell>
        <Cell name="网站链接">
          <Anchor href="https://akr.moe">akr.moe</Anchor>
        </Cell>
        <Cell name="网站描述">位于互联网边缘的小站。</Cell>
      </Table>
    </div>
  </Layout>
);

export default Submit;
