import React from "react";
import type { NextPage } from "next";
import Table from "../components/Table/Table";
import Cell from "../components/Table/TableCell";
import Layout from "../components/Layout/Layout";
import Head from "next/head";
import styles from "../styles/Form.module.css";
import "animate.css";
import Title from "../components/Title/Title";
import Anchor from "../components/Anchor/Anchor";
import Notice from "../components/Notice/Notice";

const Submit: NextPage = () => (
  <Layout width="600px">
    <Head>
      <title>Submit</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="animate__animated animate__fadeIn">
      <form className={styles.container}>
        <Title>申请友链</Title>
        <Notice>
          后端暂未准备完成，表单此时不可用，请按照格式将友链申请发送至{" "}
          <a href="mailto:akarachen@outlook.com">akarachen@outlook.com</a>
        </Notice>
        <input type="text" placeholder="昵称" className={styles.input} />
        <input type="text" placeholder="站点标题" className={styles.input} />
        <input type="url" placeholder="网站链接" className={styles.input} />
        <input type="text" placeholder="描述" className={styles.input} />
        <input type="submit" className={styles.button} />
        <input type="reset" className={styles.button} />
      </form>
      <Title>站点信息</Title>
      <Table>
        <Cell name="站点标题">AkaraChen</Cell>
        <Cell name="站点图标">
          <Anchor href="https://avatars.githubusercontent.com/u/85140972?v=4">
            Link
          </Anchor>
        </Cell>
        <Cell name="网站链接">
          <Anchor href="https://akr.moe">akr.moe</Anchor>
        </Cell>
        <Cell name="网站描述">位于互联网边缘的小站。</Cell>
      </Table>
    </div>
  </Layout>
);

export default Submit;
